### ISSUE TITLE
[Bug] DaysSinceDeath monitor shows 0 DAYS WITHOUT DEATHS even if you didn't die

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#109]
A little bug i've noticed with `DaysSinceDeath` monitor. It technically should show `ZERO DEATHS (YET)` if you didn't die in this run yet, but it just shows `0 DAYS WITHOUT DEATHS` when you take off while still being alive.

Here's an example:

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/09003f07-96a9-469f-a2e6-b795796b1667

Link to my config if you're interested:
https://pastebin.com/ZdfP3R7j

Also, since it says `ZERO DEATHS (YET)` it might be cool to also track the amount of deaths along with the days since the last one.

**Comment by ajsglist** [comment]
Adding on to this ticket, since it's a very similar issue: The "DaysSinceDeath" counter appears to ignore Company days (at least I think that's what's going on??).  It would be nice if the counter included these days for consistency with the total days played counter -- and also because players can die at the Company

![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/139426529/3bfa0fd7-3a90-444c-8154-b188ecb9ace2)

**Comment by Shaosil** [comment]
Most of this should be resolved in v1.1.8, although I'm not totally sure about the Company bit. In theory, it's supposed to be no different because this is calculated when players are revived, even if it's at the company. I'll close this for now but ping me if it's still not working as you expect.
