### ISSUE TITLE
[Bug] InternalCam and ExternalCam don't work

### ISSUE THREAD

**Issue by MathiusXII** [Shaosil/LethalCompanyMods-GeneralImprovements#153]
InternalCam and ExternalCam don't work as monitor displays. This shows up in the console...
 
  [Error  :GeneralImprovements] Could not find 'InternalCam' for monitor assignment! Please check your config is using acceptable values.
  [Error  :GeneralImprovements] Could not find 'ExternalCam' for monitor assignment! Please check your config is using acceptable values.

**Comment by Shaosil** [comment]
Do you have UseBetterMonitors set to true? If not, you cannot change the position of Internal and External cams, since they are hardcoded to use the single existing material slot on the vanilla mesh.

With UseBetterMonitors = true, I am using a custom mesh that supports more monitors, as well as supporting a camera texture OR text on any of them.

**Comment by MathiusXII** [comment]
I don’t. Doesn’t that add additional monitors on the left side? I put stuff on that table so I didn’t want to put monitors on it. Could there be a way to use those without adding additional monitors?

**Comment by Shaosil** [comment]
Ok, you can use every new monitor type _except_ the InternalCam and ExternalCam when using the vanilla monitors. Those are render textures, which I don't support on the canvas/text objects that are used. I will however add a more detailed error message in the next update. Closing for now as unplanned.
