### ISSUE TITLE
FixPersonalScanner True throws errors when used with Hold_Scan_Button

### ISSUE THREAD

**Issue by darkbrewery** [Shaosil/LethalCompanyMods-GeneralImprovements#26]
![image](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/806316/7a9c0268-a3d0-4959-a39d-57a2c9e44c54)

**Comment by darkbrewery** [comment]
BetterItemScan and Dynamic_Scanner_range also installed

**Comment by Shaosil** [comment]
I'll take a look at this 👍🏼

**Comment by Shaosil** [comment]
After checking your error log, the base game code, my own code, and BetterItemScan code, I think it's safe to say that the error is on BetterItemScan's side, not mine. I realize things may break when FixPersonalScanner is set to true, but that's because it's trying to modify the same functions as the other mod.

For now, the two options you have are 
1) Contact the dev of BetterItemScan with their error details, or
2) Choose whether to use BetterItemScan or set FixPersonalScanner to true, since they are not directly compatible.

**Comment by darkbrewery** [comment]
Thankyou for looking into this!
