### ISSUE TITLE
[1.0.6] First-person visual issue w/ RearrangeOnDrop when host lacks mod

### ISSUE THREAD

**Issue by throwitaway99** [Shaosil/LethalCompanyMods-GeneralImprovements#3]
This issue began in 1.0.2 with the introduction of the animation bug fix - in 1.0.1, the particular problem detailed in this issue was not present. When playing on a session where the host lacks the mod (and I am using the mod with its default configuration, so RearrangeOnDrop is enabled), upon dropping an item my arm will go down to the side of me w/ the item that gets slotted in its place. If I switch to another slot, and then switch back, the issue is resolved. I have also tested by creating a session as a host - and the issue is not present there. I have provided a video to demonstrate.

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/136512585/0c47ed0b-d135-40b3-b8a1-442c9f0c9c60

**Comment by throwitaway99** [comment]
Just discovered an additional thing: I again created a session as a host (with the mod enabled, of course), and this time I found that signs/shovels in particular are bugged in a distinct way, differing from what I reported above (though reproduced the same way, albeit as a host instead).


https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/136512585/47d9fdde-0c32-4cb1-b48b-b3a26b4f5f7d

**Comment by Shaosil** [comment]
Excellent and detailed videos, thanks for that. Luckily, these should also both be fixed in the latest version (v1.0.7).

Now, playing with a host that does not have it while using RearrangeOnDrop WILL cause funky desync issues with what you are holding not showing to those not having the mod, since the mod shifts slots around. But the animations should be fixed now. Marking as closed for now.
