### ISSUE TITLE
[Suggestion] Change Company sell counter changes to configurable

### ISSUE THREAD

**Issue by ajsglist** [Shaosil/LethalCompanyMods-GeneralImprovements#60]
The original variability in the sell counter bell ringing is something we have come to enjoy, and we would love to be able to disable this QoL update to the original behavior.

Thanks for the consideration

"Decreases the time required in between placing items on the company counter"

**Comment by ajsglist** [comment]
I apologize for quoting an incorrect line from the mod page.

However I don't think it's correct that GeneralImprovements doesn't change the bell behavior at the company.  With GI installed, the bell works immediately.  With GI uninstalled, the vanilla behavior of RNG bell turn-in is observed.

It would be great to have an option to retain the vanilla functionality via config.

Thanks again for your time!

**Comment by Shaosil** [comment]
Haha, well I would certainly add a config option if I touched the bell code anywhere in my mod! :)

The bell behavior is always RNG based - sometimes it can appear instantaneous (it's basically just a noise generator) and sometimes it takes a ton of presses. I've found a variety of behavior, on both ends of the spectrum, while my mod is installed (and without).

I could add an option to not decrease the "drop item" cooldown, but again that's unrelated to anything else and not a big priority since I imagine most people would want that.
