### ISSUE TITLE
Noticeable monitor color difference

### ISSUE THREAD

**Issue by NilaierMusic** [Shaosil/LethalCompanyMods-GeneralImprovements#67]
I can't really say if a new monitor colors are a stylistic choice or just an oversight, but a color for the font is a bit different from the vanilla game.
![IMG_20240125_034720](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/05937412-3048-43ab-8a07-208abe0c7446)
If that's the new style of 1.1.0, it would be cool to be able to change font's color in the config.

Also, now `ShowBlueMonitorBackground = false` doesn't have a completely black background like it used to in 1.0.27 and earlier. It's harder to notice on lower gamma, but it's much more apparent on higher ones that the background is more grayish.
![IMG_20240125_040516](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/assets/86863646/613cb9b0-f92a-4107-ac01-b94816c7be0a)

**Comment by Shaosil** [comment]
Hi there - not really an oversight or choice actually, I believe I told it to use the same texture for font and blue background color, but because it is now a camera applying its view to a render texture, and then applying that as the texture of the screen materials, it's going to look a little differnet than the plain world space canvas that's in vanilla.

However, I can add the font color to the config and darken the screens a little more :)

**Comment by NilaierMusic** [comment]
> Hi there - not really an oversight or choice actually, I believe I told it to use the same texture for font and blue background color, but because it is now a camera applying its view to a render texture, and then applying that as the texture of the screen materials, it's going to look a little different than the plain world space canvas that's in vanilla.
> 
> However, I can add the font color to the config and darken the screens a little more :)

Yeah, that would be nice to have. The colors just stand out a bit more which hurts my perfectionist brain ;)

**Comment by Shaosil** [comment]
This is now customizable in v1.1.1, going live shortly.
