### ISSUE TITLE
[Suggestion] Config option to keep default vanilla monitor bank

### ISSUE THREAD

**Issue by GaistH** [Shaosil/LethalCompanyMods-GeneralImprovements#71]
If at all possible I would really appreciate an option to stick to the original monitor bay arrangement -- really not a fan of adding the additional big monitor and changing the layout but don't want to miss out on the rest of the basic improvements.  To be honest, this change feels like a bit of scope creep after most everything else still just took care of broad baseline issues or was entirely option like the healing station.

**Comment by Shaosil** [comment]
The new monitors will only appear if you have UseBetterMonitors set to True, and by default it should be False. Did you import someone else's config profile?

Either way, setting it back to false should take care of that for you. I know I'm adding a lot of stuff in one mod, that's why I try to default them to off and let people enable what they like.

Let me know if that fixes it for you.

**Comment by GaistH** [comment]
That looks to have been the case -- thank you for making that optional, it's appreciated.
